### ISSUE TITLE
Biweekly Call

### ISSUE THREAD

**Issue by daviddias** [ipfs/dynamic-data-and-capabilities#16]
@pgte we talked about how it will be good and how we are ready to have a Weekly Call for this WG multiple times. Anything thing I can help getting this scheduled?

**Comment by pgte** [comment]
Sorry about the delay, I've been in catch-up mode after recovering from some sick days.
I'm thinking we could do a bi-weekly meeting landing on every other Tuesday 16:00 GMT.
First meeting would be on April 3rd.

@diasdavid sounds good? Since you're more familiar with who's working on what these days, it would be great if you could list some people I could invite..

**Comment by daviddias** [comment]
@fritzy, @haadcode, @dmonad for sure will be interested :) @diffcunha, @diffcunha, @olizilla, @alanshaw, @fsdiogo, @hugomrdias, @vasco-santos might be interested too.

You know what they say, "Host the Weekly Call and they will come" :)

**Comment by daviddias** [comment]
@pgte added to the calendar

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1211152/37720629-ec6c03e4-2ce4-11e8-8bac-906a0fb04c93.png">

Can you create a Zoom recurring meeting using your Zoom account (at protocol.zoom.us) and past the url here so that I can update the calendar event? Thanks!

**Comment by pgte** [comment]
@diasdavid Thanks!
Here is is: https://protocol.zoom.us/j/586782711

**Comment by pgte** [comment]
@diasdavid Just received the invitation and there is a Google Hangouts URL in there (which I think Google automatically puts). Could you remove this so that people don't get confused?

<img width="468" alt="inbox_ _protocol_labs__9_messages_" src="https://user-images.githubusercontent.com/47910/37720985-5d5c84d0-2d20-11e8-9747-47c0dbd68797.png">

**Comment by daviddias** [comment]
@pgte added and fixed

**Comment by pgte** [comment]
@diasdavid thank you! :)

**Comment by diffcunha** [comment]
@diasdavid can you send me an invite as well to diogo.f.cunha@gmail.com

**Comment by daviddias** [comment]
@diffcunha, it is better for you to subscribe to the calendar at https://github.com/ipfs/community#calendar so that you don't get spammed ad-eternum.

**Comment by pgte** [comment]
📅 [First biweekly call is today 2pm UTC!](https://github.com/ipfs/dynamic-data-and-capabilities/issues/17)

**Comment by momack2** [comment]
If there is a better place to follow along with meeting status updates (if the zoom link changes, where the crypt pad is, etc) - can we get it linked in the ipfs calendar invite? If there isn't a better place, can we open an issue like ipfs/libp2p/ipld to track this?
